
all: clang

clang:
	clang-format -i  Model/*.h  Model/*.cpp \
	Model/CommandsImplementation/*.h Model/CommandsImplementation/*.cpp \
	pathfinder2E_manager/*.cpp pathfinder2E_manager/*.h \
	CombatantWidget/*.cpp CombatantWidget/*.h \
	CombatantDialog/*.cpp CombatantDialog/*.h \
	EffectDialog/*.cpp EffectDialog/*.h \
	CommandDialog/*.cpp CommandDialog/*.h \
	CommandIcon/*.cpp CommandIcon/*.h \
	ManagerPF2E/*.cpp ManagerPF2E/*.h \
	--style=Google